### ISSUE TITLE
Richieste di aiuto

### ISSUE THREAD

**Issue by Caffo17** [cesarebernardis/samarete#10]
Questa è complicata:

Ho creato un nuovo utente e gli ho assegnato una nuova associazione creata da me.
Ho creato poi una richiesta di aiuto globale.

Gestore.adp ha il link in alto a destra "Richieste" che però cliccandolo ti lascia sulla home.
La nuova associazione e admin non hanno proprio il link "Richieste". (Admin non so se deve averlo)

**Comment by Caffo17** [comment]
Update:
Tutto a posto per gestore.adp

**Comment by cesarebernardis** [comment]
Il problema era che non venivano correttamente collegati l'associazione e l'utente. Sistemato.
