### ISSUE TITLE
Chat difettosa

### ISSUE THREAD

**Issue by Caffo17** [cesarebernardis/samarete#12]
La chat non funziona.
Chat sotto progetto di gestore.adp:
se provo a scrivere con admin e gestore.adp mi da errore
se scrivo con la nuova associazione che ho creata, invia il messaggio, ma è come se si perdesse e non viene visualizzato né da chi lo ha inviato né da chi in teoria lo dovrebbe ricevere (cioè gestore.adp)

**Comment by cesarebernardis** [comment]
Fixed
